sign_up_title               = "//h2[text()='Sign Up']"
first_name_field            = "//input[@id='firstName']"
last_name_field             = "//input[@id='lastName']"
email_field                 = "//input[@id='email']"
phone_number_field          = "//input[@id='phoneNumber']"
address_field               = "//input[@id='address']"
password_field              = "//input[@id='password']"
confirm_password_field      = "//input[@id='confirm_password']"
register_btn                = "//input[@name='register']"
login_link                  = "//a[text()='Login']"
success_info                = "//h2[text()='Success']"
ok_btn                      = "//button[text()='OK']"

#error message
first_name_error            = "//label[@id='firstName-error']"
last_name_error             = "//label[@id='lastName-error']"
email_error                 = "//label[@id='email-error']"
password_error              = "//label[@id='password-error']"
confirm_password_error      = "//label[@id='confirm_password-error']"